module.exports.descriptors = [
    'Computers',
    'Mobile phones',
    'Entertainment equipment, such as an Xbox or PlayStation',
    'Cameras',
    'Household furniture',
    'Washing machines and dishwashers',
    'Clothing',
    'Sports equipment',
    'Kitchen utensils – plates, pots and pans',
    'Choice of restaurants',
    'Hotels and airlines',
    'Luggage',
    'Getting a pet',
    'Joining a gym',
    'Hairdresser and beautician',
    'Car repairs',
    'Plants for the yard',
    'Perfumes and cosmetics',
    'Running shoes',
    'Everyday jewelry',
    'Kids bicycles',
    'Internet provider',
    'Everyday home loans and credit cards',
    'House repairs, paint, tools',
    'Regular doctor and dentist'
]